stages:
  - validate
  - security

terraform_validate:
  image:
    name: hashicorp/terraform:latest
    entrypoint: [""]
  stage: validate
  script:
    - terraform init -backend=false
    - terraform fmt -check
    - terraform validate

trivy_scan:
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  stage: security
  script:
    - trivy image --severity HIGH,CRITICAL nginx:latest